const C=window.NEXORA_COUPLE_CONFIG||{};let sb=null,map=null,meMarker=null,partnerMarker=null,watchId=null,lastPos=null,sharing=false;
const $=id=>document.getElementById(id);const toast=m=>{const t=$("toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2400)};
function initMap(){map=L.map('map',{zoomControl:false}).setView([-6.5,107.5],6);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map)}
function setConfig(){if(C.SUPABASE_URL&&C.SUPABASE_ANON_KEY)sb=supabase.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY)}
function updateSpeed(pos){let s=pos.coords.speed;if(typeof s==='number'&&s>=0){s=s*3.6}else if(lastPos){const R=6371000,a=(pos.coords.latitude-lastPos.lat)*Math.PI/180,b=(pos.coords.longitude-lastPos.lng)*Math.PI/180;const d=2*R*Math.asin(Math.sqrt(Math.sin(a/2)**2+Math.cos(lastPos.lat*Math.PI/180)*Math.cos(pos.coords.latitude*Math.PI/180)*Math.sin(b/2)**2));s=d/((pos.timestamp-lastPos.time)/1000)*3.6}else s=0;$("speed").textContent=s.toFixed(1);$("movementState").textContent=s<1?"Stationary":s<7?"Walking":"Moving";lastPos={lat:pos.coords.latitude,lng:pos.coords.longitude,time:pos.timestamp};}
function usePosition(pos){const {latitude,longitude}=pos.coords;updateSpeed(pos);if(!meMarker)meMarker=L.marker([latitude,longitude]).addTo(map).bindPopup('You');else meMarker.setLatLng([latitude,longitude]);map.setView([latitude,longitude],15);$("locationText").textContent=`${latitude.toFixed(5)}, ${longitude.toFixed(5)}`;if(sb)saveLocation(pos).catch(console.error)}
async function saveLocation(pos){const {data:{user}}=await sb.auth.getUser();if(!user)return;await sb.from('couple_locations').upsert({user_id:user.id,latitude:pos.coords.latitude,longitude:pos.coords.longitude,speed_kmh:Math.max(0,(pos.coords.speed||0)*3.6),updated_at:new Date().toISOString()},{onConflict:'user_id'});await sb.from('couple_presence').upsert({user_id:user.id,is_online:true,last_seen:new Date().toISOString()},{onConflict:'user_id'})}
function toggleLocation(){sharing=!sharing;$("locationToggle").classList.toggle('on',sharing);if(sharing){if(!navigator.geolocation)return toast('Browser tidak mendukung lokasi.');watchId=navigator.geolocation.watchPosition(usePosition,e=>toast('Permission lokasi belum diberikan.'),{enableHighAccuracy:true,maximumAge:5000,timeout:15000});toast('Location sharing aktif')}else{if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=null;toast('Location sharing dimatikan')}}
function createCode(){const code=Math.random().toString(36).slice(2,8).toUpperCase();$("generatedCode").textContent=code;navigator.clipboard?.writeText(code);toast('Kode pairing dibuat & disalin.');}
function distance(a,b){const R=6371,la=(b.lat-a.lat)*Math.PI/180,lo=(b.lng-a.lng)*Math.PI/180;const x=Math.sin(la/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(lo/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function setupPresence(){setInterval(()=>{if(sb)savePresence().catch(()=>{});$("activeDuration").textContent=`${Math.floor((Date.now()%86400000)/60000)}m`},30000)}
async function savePresence(){const {data:{user}}=await sb.auth.getUser();if(user)await sb.from('couple_presence').upsert({user_id:user.id,is_online:true,last_seen:new Date().toISOString()},{onConflict:'user_id'})}
function start(){initMap();setConfig();$("locationToggle").onclick=toggleLocation;$("createPair").onclick=createCode;$("joinPair").onclick=()=>toast('Pairing backend akan aktif setelah SQL Supabase dijalankan.');$("refreshBtn").onclick=()=>location.reload();$("centerMap").onclick=()=>meMarker&&map.setView(meMarker.getLatLng(),15);setupPresence();if(!sb)toast('Mode preview aktif — isi config.js untuk menghubungkan Supabase.');}
start();
